# Project: 4-5¶þ·Ö
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 4-5Twodevide_private.res
OBJ      = 4-5binaryDivide/main.o $(RES)
LINKOBJ  = 4-5binaryDivide/main.o $(RES)
LIBS     = -L"E:/Dev-Cpp/MinGW64/lib" -L"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 4-5Twodevide.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

4-5binaryDivide/main.o: 4-5binaryDivide/main.cpp
	$(CPP) -c 4-5binaryDivide/main.cpp -o 4-5binaryDivide/main.o $(CXXFLAGS)

4-5Twodevide_private.res: 4-5Twodevide_private.rc 
	$(WINDRES) -i 4-5Twodevide_private.rc --input-format=rc -o 4-5Twodevide_private.res -O coff 

